apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-data-pvc
  namespace: galore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pool
  namespace: galore
  labels:
    app: worker-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-pool
  template:
    metadata:
      labels:
        app: worker-pool
    spec:
      containers:
        - name: worker-pool
          image: docker.dragonflydb.io/dragonflydb/dragonfly
          imagePullPolicy: IfNotPresent
          args:
            - "--port"
            - "6380"
          ports:
            - containerPort: 6380
          volumeMounts:
            - name: worker-data
              mountPath: /data
      volumes:
        - name: worker-data
          persistentVolumeClaim:
            claimName: worker-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: worker-pool
  namespace: galore
  labels:
    app: worker-pool
spec:
  type: ClusterIP
  selector:
    app: worker-pool
  ports:
    - name: redis
      port: 6380
      targetPort: 6380


