// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreatedCocktail struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Image        string      `json:"image"`
	Ingredients  []byte      `json:"ingredients"`
	Instructions []byte      `json:"instructions"`
	Description  string      `json:"description"`
	UserID       pgtype.UUID `json:"user_id"`
	CreatedAt    time.Time   `json:"created_at"`
}

type FcmToken struct {
	ID        pgtype.UUID `json:"id"`
	Token     string      `json:"token"`
	DeviceID  string      `json:"device_id"`
	UserID    pgtype.UUID `json:"user_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type Flavour struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	CreatedAt time.Time   `json:"created_at"`
}

type LikedCocktail struct {
	CocktailID string      `json:"cocktail_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

type LikedFlavour struct {
	FlavourID pgtype.UUID `json:"flavour_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type Notification struct {
	ID               pgtype.UUID `json:"id"`
	UserID           pgtype.UUID `json:"user_id"`
	NotificationType pgtype.UUID `json:"notification_type"`
	CreatedAt        time.Time   `json:"created_at"`
}

type NotificationType struct {
	ID        pgtype.UUID `json:"id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Tag       string      `json:"tag"`
	CreatedAt time.Time   `json:"created_at"`
}

type User struct {
	ID                        pgtype.UUID `json:"id"`
	Email                     string      `json:"email"`
	Name                      string      `json:"name"`
	Password                  string      `json:"password"`
	AvatarUrl                 string      `json:"avatar_url"`
	EnabledPushNotifications  bool        `json:"enabled_push_notifications"`
	EnabledEmailNotifications bool        `json:"enabled_email_notifications"`
	CreatedAt                 time.Time   `json:"created_at"`
}
