// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetCreatedCocktails(ctx context.Context, userID pgtype.UUID) ([]CreatedCocktail, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserFCMTokens(ctx context.Context, userID pgtype.UUID) ([]FcmToken, error)
}

var _ Querier = (*Queries)(nil)
