// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m1thrandir225/galore-services/embedding_service (interfaces: EmbeddingService)
//
// Generated by this command:
//
//	mockgen -package mockembedding -destination embedding_service/mock/embedding.go github.com/m1thrandir225/galore-services/embedding_service EmbeddingService
//

// Package mockembedding is a generated GoMock package.
package mockembedding

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmbeddingService is a mock of EmbeddingService interface.
type MockEmbeddingService struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingServiceMockRecorder
}

// MockEmbeddingServiceMockRecorder is the mock recorder for MockEmbeddingService.
type MockEmbeddingServiceMockRecorder struct {
	mock *MockEmbeddingService
}

// NewMockEmbeddingService creates a new mock instance.
func NewMockEmbeddingService(ctrl *gomock.Controller) *MockEmbeddingService {
	mock := &MockEmbeddingService{ctrl: ctrl}
	mock.recorder = &MockEmbeddingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingService) EXPECT() *MockEmbeddingServiceMockRecorder {
	return m.recorder
}

// GenerateEmbedding mocks base method.
func (m *MockEmbeddingService) GenerateEmbedding(arg0 string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEmbedding", arg0)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateEmbedding indicates an expected call of GenerateEmbedding.
func (mr *MockEmbeddingServiceMockRecorder) GenerateEmbedding(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEmbedding", reflect.TypeOf((*MockEmbeddingService)(nil).GenerateEmbedding), arg0)
}
