// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: generate_cocktail_draft.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createGenerateCocktailDraft = `-- name: CreateGenerateCocktailDraft :one
INSERT INTO generate_cocktail_drafts(
         request_id,
         name,
         description,
         ingredients,
         instructions,
         main_image_prompt
)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
)
RETURNING id, request_id, name, description, instructions, ingredients, main_image_prompt, created_at
`

type CreateGenerateCocktailDraftParams struct {
	RequestID       uuid.UUID `json:"request_id"`
	Name            string    `json:"name"`
	Description     string    `json:"description"`
	Ingredients     []byte    `json:"ingredients"`
	Instructions    []byte    `json:"instructions"`
	MainImagePrompt string    `json:"main_image_prompt"`
}

func (q *Queries) CreateGenerateCocktailDraft(ctx context.Context, arg CreateGenerateCocktailDraftParams) (GenerateCocktailDraft, error) {
	row := q.db.QueryRow(ctx, createGenerateCocktailDraft,
		arg.RequestID,
		arg.Name,
		arg.Description,
		arg.Ingredients,
		arg.Instructions,
		arg.MainImagePrompt,
	)
	var i GenerateCocktailDraft
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Ingredients,
		&i.MainImagePrompt,
		&i.CreatedAt,
	)
	return i, err
}

const getCocktailDraft = `-- name: GetCocktailDraft :one
SELECT id, request_id, name, description, instructions, ingredients, main_image_prompt, created_at
FROM generate_cocktail_drafts
WHERE id = $1
`

func (q *Queries) GetCocktailDraft(ctx context.Context, id uuid.UUID) (GenerateCocktailDraft, error) {
	row := q.db.QueryRow(ctx, getCocktailDraft, id)
	var i GenerateCocktailDraft
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Ingredients,
		&i.MainImagePrompt,
		&i.CreatedAt,
	)
	return i, err
}
