// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: generate_cocktail_request.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createGenerateCocktailRequest = `-- name: CreateGenerateCocktailRequest :one
INSERT INTO
generate_cocktail_requests(user_id, prompt, status)
VALUES ($1, $2, 'generating_cocktail')
RETURNING id, user_id, prompt, status, error_message, updated_at, created_at
`

type CreateGenerateCocktailRequestParams struct {
	UserID uuid.UUID `json:"user_id"`
	Prompt string    `json:"prompt"`
}

func (q *Queries) CreateGenerateCocktailRequest(ctx context.Context, arg CreateGenerateCocktailRequestParams) (GenerateCocktailRequest, error) {
	row := q.db.QueryRow(ctx, createGenerateCocktailRequest, arg.UserID, arg.Prompt)
	var i GenerateCocktailRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Prompt,
		&i.Status,
		&i.ErrorMessage,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserGenerationRequests = `-- name: GetUserGenerationRequests :many
SELECT id, user_id, prompt, status, error_message, updated_at, created_at FROM generate_cocktail_requests
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserGenerationRequests(ctx context.Context, userID uuid.UUID) ([]GenerateCocktailRequest, error) {
	rows, err := q.db.Query(ctx, getUserGenerationRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GenerateCocktailRequest{}
	for rows.Next() {
		var i GenerateCocktailRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Prompt,
			&i.Status,
			&i.ErrorMessage,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
