// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: generate_cocktail_draft.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createGenerateCocktailDraft = `-- name: CreateGenerateCocktailDraft :one
INSERT INTO generate_cocktail_drafts(
         request_id,
         name,
         description,
         ingredients,
         instructions,
         main_image_prompt,
         steps_image_prompts
)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
)
RETURNING id, request_id, name, description, instructions, ingredients, main_image_prompt, steps_image_prompts, created_at
`

type CreateGenerateCocktailDraftParams struct {
	RequestID         uuid.UUID `json:"request_id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	Ingredients       []byte    `json:"ingredients"`
	Instructions      []byte    `json:"instructions"`
	MainImagePrompt   string    `json:"main_image_prompt"`
	StepsImagePrompts []string  `json:"steps_image_prompts"`
}

func (q *Queries) CreateGenerateCocktailDraft(ctx context.Context, arg CreateGenerateCocktailDraftParams) (GenerateCocktailDraft, error) {
	row := q.db.QueryRow(ctx, createGenerateCocktailDraft,
		arg.RequestID,
		arg.Name,
		arg.Description,
		arg.Ingredients,
		arg.Instructions,
		arg.MainImagePrompt,
		arg.StepsImagePrompts,
	)
	var i GenerateCocktailDraft
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Ingredients,
		&i.MainImagePrompt,
		&i.StepsImagePrompts,
		&i.CreatedAt,
	)
	return i, err
}
