name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: m1thrandir
  # You'll need to add DOCKER_PASSWORD as a secret in your GitHub repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'api-service',
          'categorize-service',
          'embedding-service',
          'migration-service'
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/galore:${{ matrix.service }}-latest
            ${{ env.DOCKER_USERNAME }}/galore:${{ matrix.service }}-${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/galore:${{ matrix.service }}-latest
          cache-to: type=inline